name: E2E test

on:
  pull_request:
    branches:
      - develop
jobs:
  build: 
    uses: 10up/maps-block-apple/.github/workflows/build-release-zip.yml@update/151 # TODO: Update this to develop branch.
  cypress:
    name: ${{ matrix.core.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.8'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download build zip
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.event.repository.name }}
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Set the core version and plugins config 
      run: ./tests/bin/set-wp-config.js --core=${{ matrix.core.version }} --plugins=./${{ github.event.repository.name }}
    - name: Set up WP environment
      run: npm run env:start
    - name: Test
      run: npm run cypress:run
      env:
        CYPRESS_MAPS_PRIVATE_KEY: ${{ secrets.MAPS_PRIVATE_KEY }}
        CYPRESS_MAPS_KEY_ID: ${{ secrets.MAPS_KEY_ID }}
        CYPRESS_MAPS_TEAM_ID: ${{ secrets.MAPS_TEAM_ID }}
